"""empty message

Revision ID: 0368c28d6b66
Revises: 66250c2394f9
Create Date: 2026-05-18 09:59:17.752376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0368c28d6b66'
down_revision = '66250c2394f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('personaje')
    op.drop_table('favorito')
    op.drop_table('planeta')
    op.drop_table('vehiculo')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('user_correo_key', type_='unique')
        batch_op.drop_constraint('user_nombre_usuario_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('correo')
        batch_op.drop_column('nombre_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_usuario', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_nombre_usuario_key', ['nombre_usuario'])
        batch_op.create_unique_constraint('user_correo_key', ['correo'])
        batch_op.drop_column('birth_date')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    op.create_table('vehiculo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehiculo_pkey')
    )
    op.create_table('planeta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clima', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planeta_pkey')
    )
    op.create_table('favorito',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_elemento', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('elemento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorito_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_pkey')
    )
    op.create_table('personaje',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genero', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='personaje_pkey')
    )
    op.drop_table('favoritos')
    # ### end Alembic commands ###
