"""empty message

Revision ID: 152908e2bbc4
Revises: 0368c28d6b66
Create Date: 2026-05-18 10:10:16.085417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152908e2bbc4'
down_revision = '0368c28d6b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_heroe', sa.String(length=120), nullable=False),
    sa.Column('apariciones_comics', sa.Integer(), nullable=False),
    sa.Column('ciudad_base', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_heroe')
    )
    op.create_table('marvel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_heroe', sa.String(length=120), nullable=False),
    sa.Column('nivel_poder', sa.Integer(), nullable=False),
    sa.Column('afiliacion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_heroe')
    )
    op.create_table('other',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_heroe', sa.String(length=120), nullable=False),
    sa.Column('universo_origen', sa.String(length=120), nullable=False),
    sa.Column('año_creacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_heroe')
    )
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_marvel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_dc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_other', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dc', ['id_dc'], ['id'])
        batch_op.create_foreign_key(None, 'other', ['id_other'], ['id'])
        batch_op.create_foreign_key(None, 'marvel', ['id_marvel'], ['id'])
        batch_op.drop_column('hero_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_other')
        batch_op.drop_column('id_dc')
        batch_op.drop_column('id_marvel')

    op.drop_table('other')
    op.drop_table('marvel')
    op.drop_table('dc')
    # ### end Alembic commands ###
