"""empty message

Revision ID: 81080cc9250c
Revises: 
Create Date: 2026-05-22 09:22:41.194413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81080cc9250c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_heroe', sa.String(length=120), nullable=False),
    sa.Column('apariciones_comics', sa.Integer(), nullable=False),
    sa.Column('ciudad_base', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_heroe')
    )
    op.create_table('marvel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_heroe', sa.String(length=120), nullable=False),
    sa.Column('nivel_poder', sa.Integer(), nullable=False),
    sa.Column('afiliacion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_heroe')
    )
    op.create_table('other',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_heroe', sa.String(length=120), nullable=False),
    sa.Column('universo_origen', sa.String(length=120), nullable=False),
    sa.Column('año_creacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_heroe')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_marvel', sa.Integer(), nullable=True),
    sa.Column('id_dc', sa.Integer(), nullable=True),
    sa.Column('id_other', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dc'], ['dc.id'], ),
    sa.ForeignKeyConstraint(['id_marvel'], ['marvel.id'], ),
    sa.ForeignKeyConstraint(['id_other'], ['other.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    op.drop_table('user')
    op.drop_table('other')
    op.drop_table('marvel')
    op.drop_table('dc')
    # ### end Alembic commands ###
